--DESC BOOK;
INSERT INTO BOOK (ISBN, THUM_IMG, BOOK_NAME, AUTHOR, PUBLISHER, CATEGORY, BOOK_INTRO, AUTH_INTRO, PUB_INTRO, BOOK_PAGE, TOTAL_GRADE, GRADE_PEO)
    VALUES('1234567891011', NULL, '도서', '저자', '출판사', '카테고리', '책소개', '저자소개', '출판사서평', 153, 8.6, 123);
SELECT * FROM BOOK;

--DESC SUBSCRIBE;
INSERT INTO SUBSCRIBE (SUBTYPE, SUBTERM, SUBPRICE) VALUES(1, 30, 12800);
SELECT * FROM SUBSCRIBE;

--DESC MEMBER;
INSERT INTO MEMBER (ID, PWD, NAME, EMAIL, ISSUB, SUBTYPE, SUBSTR_DATE, SUBEND_DATE)
    VALUES('aab1', 'abc123', '이름', 'aab1@gmail.com', 'Y', 1, SYSDATE, SYSDATE+30);
INSERT INTO MEMBER (ID, PWD, NAME, EMAIL, ISSUB, SUBTYPE, SUBSTR_DATE, SUBEND_DATE)
    VALUES('abcd222', 'abcd', '이름2', 'abcd222@gmail.com', 'N', NULL, NULL, NULL);
SELECT * FROM MEMBER;

--DESC LOVE_ADD;
INSERT INTO LOVE_ADD (ID, ISBN) VALUES('aab1', '1234567891011');
SELECT * FROM LOVE_ADD;

--DESC READING_NOW;
INSERT INTO READING_NOW (READ_PAGE, READSTR_DATE, ID, ISBN) VALUES (36, SYSDATE, 'aab1', '1234567891011');
SELECT * FROM READING_NOW;

--DESC REVIEW;
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (1, '1234567891011', '초반부 전개가 흥미로워요', SYSDATE, 4, 'aab1');
SELECT * FROM REVIEW;

COMMIT;

DELETE FROM MEMBER WHERE ID = 'abcd222';
DELETE FROM REVIEW;
DELETE FROM READING_NOW;
DELETE FROM LOVE_ADD;
DELETE FROM MEMBER;
DELETE FROM SUBSCRIBE;
DELETE FROM BOOK;

COMMIT;
