--DESC BOOK;
INSERT INTO BOOK (ISBN, THUM_IMG, BOOK_NAME, AUTHOR, PUBLISHER, CATEGORY, BOOK_INTRO, AUTH_INTRO, PUB_INTRO, BOOK_PAGE, TOTAL_GRADE, GRADE_PEO)
    VALUES('1234567891011', NULL, '도서', '저자', '출판사', '카테고리', '책소개', '저자소개', '출판사서평', 153, 8.6, 123);
SELECT * FROM BOOK;

--DESC SUBSCRIBE;
INSERT INTO SUBSCRIBE (SUBTYPE, SUBTERM, SUBPRICE) VALUES(1, 30, 12800);
INSERT INTO SUBSCRIBE (SUBTYPE, SUBTERM, SUBPRICE) VALUES(2, 60, 23500);
INSERT INTO SUBSCRIBE (SUBTYPE, SUBTERM, SUBPRICE) VALUES(3, 90, 34400);
SELECT * FROM SUBSCRIBE;

--DESC MEMBER;
INSERT INTO MEMBER (ID, PWD, NAME, EMAIL, ISSUB, SUBTYPE, SUBSTR_DATE, SUBEND_DATE)
    VALUES('abc123', 'abc123', '이름', 'abc123@gmail.com', 'Y', 1, SYSDATE, SYSDATE+30);
INSERT INTO MEMBER (ID, PWD, NAME, EMAIL, ISSUB, SUBTYPE, SUBSTR_DATE, SUBEND_DATE)
    VALUES('abcd222', 'abcd', '이름2', 'abcd222@gmail.com', 'N', NULL, NULL, NULL);
INSERT INTO MEMBER (ID, PWD, NAME, EMAIL, ISSUB, SUBTYPE, SUBSTR_DATE, SUBEND_DATE)
    VALUES('bb', 'bb', '이름3', 'bb@gmail.com', 'Y', 2, SYSDATE, SYSDATE+60);
INSERT INTO MEMBER (ID, PWD, NAME, EMAIL, ISSUB, SUBTYPE, SUBSTR_DATE, SUBEND_DATE)
    VALUES('cc', 'cc', '이름4', 'cc@gmail.com', 'Y', 3, SYSDATE, SYSDATE+90);
SELECT * FROM MEMBER;

--DESC LOVE_ADD;
INSERT INTO LOVE_ADD (ID, ISBN) VALUES('aab1', '1234567891011');
SELECT * FROM LOVE_ADD;

--DESC READING_NOW;
INSERT INTO READING_NOW (READ_PAGE, READSTR_DATE, ID, ISBN) VALUES (36, SYSDATE, 'aab1', '1234567891011');
SELECT * FROM READING_NOW;

--DESC REVIEW;
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (1, '1234567891011', '초반부 전개가 흥미로워요', SYSDATE, 4, 'aab1');
SELECT * FROM REVIEW;

COMMIT;

DELETE FROM MEMBER WHERE ID = 'abcd222';
DELETE FROM REVIEW;
DELETE FROM READING_NOW;
DELETE FROM LOVE_ADD;
DELETE FROM MEMBER;
DELETE FROM SUBSCRIBE;
DELETE FROM BOOK;

COMMIT;

--review example
desc review;
delete from review;
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (1, '9791156751298', '초반부 전개가 흥미로워요', SYSDATE, 4, 'abc123');
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (2, '9791156751298', '흥미로워요', SYSDATE, 4, 'abc123');
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (3, '9791156751298', '재밌어요', SYSDATE, 4, 'abc123');
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (4, '9791156751298', '생각보다는 별로예요', SYSDATE, 2, 'abc123');
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (5, '9791156751298', '추천합니다!', SYSDATE, 5, 'abc123');
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (6, '9791156751298', '적당히 읽기 좋습니다...', SYSDATE, 3, 'abc123');
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (7, '9791156751298', '오랜만에 푹빠져서 읽었네요.', SYSDATE, 5, 'abc123');

INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (8, '9791190090780', '좋아요', SYSDATE, 4, 'abc123');
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (9, '9791190090780', '추천합니다!', SYSDATE, 5, 'abc123');
INSERT INTO REVIEW (REV_NUM, ISBN, REV_TXT, REV_DATE, EACH_GRADE, ID) VALUES (10, '9791190090780', '괜찮은듯요', SYSDATE, 4, 'abc123');

SELECT * FROM BOOK WHERE ROWNUM <= 5;
SELECT * FROM (SELECT * FROM BOOK WHERE CATEGORY LIKE '%에세이%') WHERE ROWNUM <= 5;

SELECT * FROM LOVE_ADD WHERE ID='abc123' AND ISBN='9791191432008';


