--DROP TABLE
DROP TABLE  REVIEW;
DROP TABLE  LOVE_ADD;
DROP TABLE  READING_NOW;
DROP TABLE  MEMBER;
DROP TABLE  SUBSCRIBE;
DROP TABLE  BOOK;


--CREATE TABLE
CREATE TABLE BOOK (
	 ISBN 	VARCHAR2(13)		NOT NULL,
	 THUM_IMG 	VARCHAR2(200),
	 BOOK_NAME 	VARCHAR2(300)		NOT NULL,
	 AUTHOR 	VARCHAR2(200)		NOT NULL,
	 PUBLISHER 	VARCHAR2(50)		NOT NULL,
	 CATEGORY 	VARCHAR2(120)		NOT NULL,
	 BOOK_INTRO 	CLOB,
	 AUTH_INTRO     VARCHAR2(500),
	 PUB_INTRO 	    CLOB,
	 BOOK_PAGE 	NUMBER,
	 TOTAL_GRADE 	NUMBER(3,1),
	 GRADE_PEO 	NUMBER
);

COMMENT ON COLUMN  BOOK . ISBN  IS '-제외,숫자만13자리';
COMMENT ON COLUMN  BOOK . BOOK_PAGE  IS '전체 쪽수';
COMMENT ON COLUMN  BOOK . TOTAL_GRADE  IS '전체별점평균';
COMMENT ON COLUMN  BOOK . GRADE_PEO  IS '전체리뷰인원';

CREATE TABLE  SUBSCRIBE  (
	 SUBTYPE 	NUMBER		NOT NULL,
	 SUBTERM 	NUMBER		NOT NULL,
	 SUBPRICE 	NUMBER		NOT NULL
);

COMMENT ON COLUMN  SUBSCRIBE . SUBTYPE  IS '0,1,2';
COMMENT ON COLUMN  SUBSCRIBE . SUBTERM  IS '각 구독권 기간';

CREATE TABLE  MEMBER  (
	 ID 	VARCHAR2(12)		NOT NULL,
	 PWD 	VARCHAR2(20)		NOT NULL,
	 NAME 	VARCHAR2(100)		NOT NULL,
	 EMAIL 	VARCHAR2(100)		NOT NULL,
	 ISSUB 	CHAR(1)		NOT NULL,
	 SUBTYPE 	NUMBER,
	 SUBSTR_DATE 	TIMESTAMP,
	 SUBEND_DATE 	TIMESTAMP
);

COMMENT ON COLUMN  MEMBER . ID  IS '4-12자리 영문자,숫자';
COMMENT ON COLUMN  MEMBER . PWD  IS '8-20자리 영문자,숫자,특수문자';
COMMENT ON COLUMN  MEMBER . ISSUB  IS 'Y/N';
COMMENT ON COLUMN  MEMBER . SUBTYPE  IS '0,1,2';
COMMENT ON COLUMN  MEMBER . SUBSTR_DATE  IS '구독 시작 날짜';
COMMENT ON COLUMN  MEMBER . SUBEND_DATE  IS '구독 종료 날짜';

CREATE TABLE  READING_NOW  (
	 READ_PAGE 	NUMBER	DEFAULT 0	NOT NULL,
	 READSTR_DATE 	DATE,
	 ID 	VARCHAR2(12)		NOT NULL,
	 ISBN 	VARCHAR2(13)		NOT NULL
);

COMMENT ON COLUMN  READING_NOW . ID  IS '4-12자리 영문자,숫자';
COMMENT ON COLUMN  READING_NOW . ISBN  IS '-제외,숫자만13자리';

CREATE TABLE  LOVE_ADD  (
	 ID 	VARCHAR2(12)		NOT NULL,
	 ISBN 	VARCHAR2(13)		NOT NULL
);

COMMENT ON COLUMN  LOVE_ADD . ID  IS '4-12자리 영문자,숫자';
COMMENT ON COLUMN  LOVE_ADD . ISBN  IS '-제외,숫자만13자리';

CREATE TABLE  REVIEW  (
	 REV_NUM 	NUMBER		NOT NULL,
	 ISBN 	VARCHAR2(13)		NOT NULL,
	 REV_TXT 	VARCHAR2(300)		NOT NULL,
	 REV_DATE 	TIMESTAMP		NOT NULL,
	 EACH_GRADE 	NUMBER		NOT NULL,
	 ID 	VARCHAR2(12)		NOT NULL
);

COMMENT ON COLUMN  REVIEW . ISBN  IS '-제외,숫자만13자리';
COMMENT ON COLUMN  REVIEW . REV_TXT  IS '100자 제한';
COMMENT ON COLUMN  REVIEW . EACH_GRADE  IS '1-5정수,별개수';
COMMENT ON COLUMN  REVIEW . ID  IS '4-12자리 영문자,숫자';

--ALTER TABLE ADD CONSTRAINT
ALTER TABLE  BOOK  ADD CONSTRAINT  PK_BOOK  PRIMARY KEY (
	 ISBN 
);
ALTER TABLE  SUBSCRIBE  ADD CONSTRAINT  PK_SUBSCRIBE  PRIMARY KEY (
	 SUBTYPE 
);
ALTER TABLE  MEMBER  ADD CONSTRAINT  PK_MEMBER  PRIMARY KEY (
	 ID 
);
ALTER TABLE  LOVE_ADD  ADD CONSTRAINT  PK_LOVE_ADD  PRIMARY KEY (
	 ID ,
	 ISBN 
);
ALTER TABLE  REVIEW  ADD CONSTRAINT  PK_REVIEW  PRIMARY KEY (
	 REV_NUM ,
	 ISBN 
);

ALTER TABLE  MEMBER  ADD CONSTRAINT  FK_SUBSCRIBE_TO_MEMBER_1  FOREIGN KEY (
	 SUBTYPE 
)
REFERENCES  SUBSCRIBE  (
	 SUBTYPE 
);

ALTER TABLE  LOVE_ADD  ADD CONSTRAINT  FK_MEMBER_TO_LOVE_ADD_1  FOREIGN KEY (
	 ID 
)
REFERENCES  MEMBER  (
	 ID 
);

ALTER TABLE  LOVE_ADD  ADD CONSTRAINT  FK_BOOK_TO_LOVE_ADD_1  FOREIGN KEY (
	 ISBN 
)
REFERENCES  BOOK  (
	 ISBN 
);

ALTER TABLE  READING_NOW  ADD CONSTRAINT  FK_MEMBER_TO_READING_NOW_1  FOREIGN KEY (
	 ID
)
REFERENCES  MEMBER  (
	 ID 
);

ALTER TABLE  READING_NOW  ADD CONSTRAINT  FK_BOOK_TO_READING_NOW_1  FOREIGN KEY (
	 ISBN 
)
REFERENCES  BOOK  (
	 ISBN 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  FK_BOOK_TO_REVIEW_1  FOREIGN KEY (
	 ISBN 
)
REFERENCES  BOOK  (
	 ISBN 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  FK_MEMBER_TO_REVIEW_1  FOREIGN KEY (
	 ID 
)

REFERENCES  MEMBER  (
	 ID 
);

ALTER TABLE REVIEW MODIFY REV_NUM NULL;
